#!/bin/bash
set -e

# Configuration
SRC_DIR="src/main/java/com/mrbt/orbit"
OUTPUT="architect/architecture-graph.md"
BASE_PKG="com.mrbt.orbit"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Validation
if [ ! -d "$SRC_DIR" ]; then
  echo "Error: $SRC_DIR not found. Run from project root."
  exit 1
fi

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT")"

# Discover modules (directories with .java files)
MODULES=()
for dir in "$SRC_DIR"/*/; do
  module=$(basename "$dir")
  MODULES+=("$module")
done

# Counters for summary
TOTAL_ENDPOINTS=0
TOTAL_ENTITIES=0

# Start output
cat > "$OUTPUT" << EOF
<!-- AUTO-GENERATED by scripts/generate-architecture-graph.sh -->
<!-- Do not edit manually. Regenerate with: ./scripts/generate-architecture-graph.sh -->
<!-- Generated: $TIMESTAMP -->

# Orbit Architecture Graph

EOF

# --- Section 1: Module Overview & Layer Completeness ---
echo "## 1. Module Overview & Layer Completeness" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Module | api | core | infrastructure | exception |" >> "$OUTPUT"
echo "|--------|-----|------|----------------|-----------|" >> "$OUTPUT"

for module in "${MODULES[@]}"; do
  api="—"; core="—"; infra="—"; exc="—"
  [ -d "$SRC_DIR/$module/api" ] && api="✓"
  [ -d "$SRC_DIR/$module/core" ] && core="✓"
  [ -d "$SRC_DIR/$module/infrastructure" ] && infra="✓"
  [ -d "$SRC_DIR/$module/exception" ] && exc="✓"
  echo "| $module | $api | $core | $infra | $exc |" >> "$OUTPUT"
done
echo "" >> "$OUTPUT"

# --- Section 2: Module Dependency Graph ---
echo "## 2. Module Dependency Graph" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo '```mermaid' >> "$OUTPUT"
echo "graph TD" >> "$OUTPUT"

# Collect unique edges using a temp file (bash 3.2 compatible)
EDGE_TMP=$(mktemp)
trap "rm -f $EDGE_TMP" EXIT

for module in "${MODULES[@]}"; do
  if [ -d "$SRC_DIR/$module" ]; then
    deps=$(grep -rh "^import ${BASE_PKG}\." "$SRC_DIR/$module" 2>/dev/null \
      | sed "s/import ${BASE_PKG}\.\([a-z_]*\)\..*/\1/" \
      | sort -u)
    for dep in $deps; do
      # Skip self-imports and cross-cutting modules
      if [ "$dep" != "$module" ] && [ "$dep" != "common" ] && [ "$dep" != "config" ]; then
        edge="${module}|${dep}"
        if ! grep -qx "$edge" "$EDGE_TMP" 2>/dev/null; then
          echo "$edge" >> "$EDGE_TMP"
          echo "  $module --> $dep" >> "$OUTPUT"
        fi
      fi
    done
  fi
done

echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Section 3: Cross-cutting Dependencies ---
echo "## 3. Cross-cutting Dependencies" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "| Module | common | config | security |" >> "$OUTPUT"
echo "|--------|--------|--------|----------|" >> "$OUTPUT"

CROSS_MODULES="common config security"
for module in "${MODULES[@]}"; do
  # Skip cross-cutting modules themselves
  is_cross=false
  for cross in $CROSS_MODULES; do
    [ "$module" = "$cross" ] && is_cross=true
  done
  $is_cross && continue

  row="| $module"
  for cross in $CROSS_MODULES; do
    count=$(grep -rh "^import ${BASE_PKG}\.${cross}\." "$SRC_DIR/$module" 2>/dev/null | wc -l | tr -d ' ')
    if [ "$count" -gt 0 ]; then
      row="$row | ✓ ($count)"
    else
      row="$row | —"
    fi
  done
  echo "$row |" >> "$OUTPUT"
done
echo "" >> "$OUTPUT"

# --- Section 4: Key Classes Per Module ---
echo "## 4. Key Classes Per Module" >> "$OUTPUT"
echo "" >> "$OUTPUT"

for module in "${MODULES[@]}"; do
  echo "### $module" >> "$OUTPUT"
  echo "" >> "$OUTPUT"

  # Controllers
  controllers=$(grep -rl "@RestController" "$SRC_DIR/$module" 2>/dev/null \
    | xargs -I{} basename {} .java 2>/dev/null | sort)
  if [ -n "$controllers" ]; then
    echo "**Controllers:** $(echo $controllers | sed 's/ /, /g')" >> "$OUTPUT"
  fi

  # Services
  services=$(grep -rl "@Service" "$SRC_DIR/$module" 2>/dev/null \
    | xargs -I{} basename {} .java 2>/dev/null | sort)
  if [ -n "$services" ]; then
    echo "**Services:** $(echo $services | sed 's/ /, /g')" >> "$OUTPUT"
  fi

  # Entities
  entities=$(grep -rl "@Entity" "$SRC_DIR/$module" 2>/dev/null \
    | xargs -I{} basename {} .java 2>/dev/null | sort)
  if [ -n "$entities" ]; then
    echo "**Entities:** $(echo $entities | sed 's/ /, /g')" >> "$OUTPUT"
    TOTAL_ENTITIES=$((TOTAL_ENTITIES + $(echo "$entities" | wc -w)))
  fi

  # Repositories
  repos=$(grep -rl "JpaRepository\|CrudRepository" "$SRC_DIR/$module" 2>/dev/null \
    | xargs -I{} basename {} .java 2>/dev/null | sort)
  if [ -n "$repos" ]; then
    echo "**Repositories:** $(echo $repos | sed 's/ /, /g')" >> "$OUTPUT"
  fi

  echo "" >> "$OUTPUT"
done
