server {
    listen 3000;
    root /usr/share/nginx/html;

    location = / {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        return 302 /orbit-api/en;
    }

    location /orbit-api {
        try_files $uri $uri.html $uri/index.html =404;
    }
}
